CREATE TABLE `auto_seo_articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`autoSeoId` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`content` longtext NOT NULL,
	`contentMarkdown` longtext,
	`metaDescription` varchar(160),
	`metaKeywords` varchar(500),
	`searchTerms` varchar(500),
	`heroImage` varchar(1000),
	`infographic` varchar(1000),
	`category` varchar(100) NOT NULL DEFAULT 'Saúde',
	`author` varchar(255) DEFAULT 'Total Quality',
	`authorRole` varchar(255) DEFAULT 'Equipe Médica',
	`readTime` varchar(50) DEFAULT '5 min',
	`status` enum('synced','published','archived','draft') NOT NULL DEFAULT 'synced',
	`publishedAt` timestamp,
	`viewCount` int DEFAULT 0,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `auto_seo_articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `auto_seo_articles_autoSeoId_unique` UNIQUE(`autoSeoId`),
	CONSTRAINT `auto_seo_articles_slug_unique` UNIQUE(`slug`)
);
